// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDownload(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddDownload'](arg1, arg2, arg3, arg4);
}

export function AllDownloads() {
  return window['go']['main']['App']['AllDownloads']();
}

export function CancelDownload(arg1) {
  return window['go']['main']['App']['CancelDownload'](arg1);
}

export function GetDefaultDownloadPath() {
  return window['go']['main']['App']['GetDefaultDownloadPath']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function PauseDownload(arg1) {
  return window['go']['main']['App']['PauseDownload'](arg1);
}

export function ResumeDownload(arg1) {
  return window['go']['main']['App']['ResumeDownload'](arg1);
}

export function ShowDirectoryDialog(arg1) {
  return window['go']['main']['App']['ShowDirectoryDialog'](arg1);
}

export function ShowFileDialog(arg1, arg2) {
  return window['go']['main']['App']['ShowFileDialog'](arg1, arg2);
}
