name: Wails build

on:
  push:
    branches:
      - master
    tags:
      - "v*"

env:
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build:
          [
            { name: d4c, platform: linux/amd64, os: ubuntu-latest },
            { name: d4c, platform: windows/amd64, os: windows-latest },
            { name: d4c, platform: darwin/universal, os: macos-latest },
          ]
    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: pnpm/action-setup@v2
        with:
          version: 10.7
      - uses: dAppServer/wails-build-action@main
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          build-obfuscate: true
          go-version: "1.23"
          node-version: "20.x"
